package com.drools.point
import com.drools.PointDomain

rule birthdayPoint
    //过生日,则加10分,并且将当月交易比翻倍后再计算积分
   salience 100
   lock-on-active true
   when
     $pointDomain : PointDomain(birthDay == true)
    then
          $pointDomain.setPoint($pointDomain.getPoint()+10);
          $pointDomain.setBuyNums($pointDomain.getBuyNums()*2);
          $pointDomain.setBuyMoney($pointDomain.getBuyMoney()*2);
          $pointDomain.setBillThisMonth($pointDomain.getBillThisMonth()*2);
          $pointDomain.recordPointLog($pointDomain.getUsername(),"birthdayPoint");
     end

rule billThisMonthPoint
  salience 99
  lock-on-active true
  date-effective "2016-11-24 23:59:59"
  date-expires "2016-12-24 23:59:59"
  when
     $pointDomain : PointDomain(billThisMonth>3)
     then
        $pointDomain.setPoint($pointDomain.getPoint()+ $pointDomain.getBillThisMonth()/3 *30);
        $pointDomain.recordPointLog($pointDomain.getUsername(),"billThisMonthPoint");
      end

 rule buyMoneyPoint
         salience 98
         lock-on-active true
         when
         $pointDomain : PointDomain(buyMoney >= 100)
         then
             $pointDomain.setPoint($pointDomain.getPoint() + (int)$pointDomain.getBuyMoney()/100 *10);
             $pointDomain.recordPointLog($pointDomain.getUsername(),"buyMonthPoint");
          end
rule buyMunsPoint
          salience 97
          lock-on-active true
          when
           $pointDomain : PointDomain(buyNums >= 5)
          then
           $pointDomain.setPoint($pointDomain.getPoint() + $pointDomain.getBuyNums() / 5 * 50);
           $pointDomain.recordPointLog($pointDomain.getUsername(),"buyNumsPoint");
          end
rule allFitPoint
          salience 96
          lock-on-active true
          when
           $pointDomain: PointDomain(buyNums >= 5 && billThisMonth >= 3 && buyMoney >= 100)
          then
           $pointDomain.setPoint($pointDomain.getPoint() + 100);
           $pointDomain.recordPointLog($pointDomain.getUsername(),"allFitPoint");
          end