package com.drools.point
import com.drools.PointDomain

rule subBackNumnsPoint
   salience 10
   lock-on-active true
   when
    $pointDomain : PointDomain(backNums >= 1)
    then
    $pointDomain.setPoint($pointDomain.getPoint() - 10);
    $pointDomain.recordPointLog($pointDomain.getUsername(),"subBackNumbsPoint");
     end

rule  subBackMondyPoint
   salience 9
    when
     $pointDomain : PointDomain(backMondy >= 100)
      then
       $pointDomain.setPoint($pointDomain.getPoint()-10);
       $pointDomain.recordPointLog($pointDomain.getUsername(),"subBackMondyPoint");
      end